### ISSUE TITLE
Replace TableFormat enum with extensible config file

### ISSUE THREAD

**Issue by ashvina** [onetable-io/onetable#13]
`TableFormat enum` should be removed from `OneTable` as it restricts extensibility. Currently it forces a rebuild if a new format needs to be supported. In practice, there could be multiple versions of the open formats and users may have their own formats also.
One option is to externalize the list of clients in a config file, which contains a default list of client names associated with default implementations and configurations.

**Comment by lmccay** [comment]
@ashvina , @the-other-tim-brown - It seems there has been extensibility work done in the #9 PR.
I'm not sure whether this issue is still valid or not.

I was thinking that a more dynamic classpath approach would have been a good way to replace what is in TableFormatClientFactory and provide the extensibility ServiceLoader and a getName() on the TargetClient interface.

This would allow you to load all implementations of TargetClient from the classpath and filter it based on the String name provided via the programming model. Removes the need for a separate config file approach.

Thoughts?

**Comment by the-other-tim-brown** [comment]
@lmccay We were hoping to do something like you've proposed. It would be great to allow people to write their own implementations of both sources and targets without requiring them to be committed to OneTable if they are proprietary (thinking internal format or tool wanting to sync to an open format). So my only suggestion is to try to make this work for sources as well if you're up for it :)

**Comment by lmccay** [comment]
@the-other-tim-brown - sure, let me take a closer look.

**Comment by lmccay** [comment]
@the-other-tim-brown - I've been trying to see what providing the ServiceLoader mechanism to the Source clients would work and I'm not sure of the goal of that. It seems based on demo and test code that explicitly instantiating the source client is part of the programming model. We could abstract it with a factory call that took a name like "HUDI" which internally found the SourceClientProvider by that name but it would definitely change the programming model exposed to the client app. Is that what you have in mind?

**Comment by lmccay** [comment]
I do actually find the:

oneTableClient.sync(perTableConfig, hudiSourceClientProvider)

kind of awkward of a model though. Something about passing a clientProvider into a client seems off.

oneTableClient.sync(SyncContext ctx) where the source and target formats and other config are contained in the ctx would feel better. You can hide the fact that there is a SourceClientProvider abstraction completely this way. The mix of iceberg and hudi specifics in the perTableConfig also feels a bit odd.

At any rate, adding a new signature to the OneTableClient to hide the other client details could be a way to migrate to this new model. If that is something you are looking to do. Otherwise, if you can indicate where else the dynamic source client lookup would help, I can take a look at that.

**Comment by the-other-tim-brown** [comment]
@lmccay I think the naming is open to changes if you have some in mind that will make things more clear. I think everything being a "client" is not really accurately representing things. Some are more like a reader or writer.

I like the idea of packing the format specific configs in some other object. 

With respect to making things more configurable, do you think it makes sense to pass in the target clients similar to how we're passing in the source client provider? That way users calling the java code directly can just instantiate some objects and pass them in. The factories can then be moved over to the utility class that allows users to run from the command line.

**Comment by lmccay** [comment]
@the-other-tim-brown  - Sounds like there is still some flexibility for the programming model here - that's good.
I started looking at how to add the ServiceLoader bit for just the TargetClients for now and it is going to require a bit of refactoring/surgery.

* Clients will need to all have zero arg contructors - looking at adding an instantiate and set properties then init() to pass in the perTableConfig and hadoop Configuration class to do what the ctor are doing
* Interfaces created for the various configuration and other classes that are needed in order to avoid adding a dependency in the spi module on the core which would be broken. So, I would add interfaces in the spi layer that the core layer would implement.
* Changes to the ClientTarget and all the implementations to add a getTableFormatName() and the init() pattern and have the existing ctor's call the init()

NOTE: I am ignoring figuring out the details of what seem to be table (hudi for instance) specific config files for now as I am ignorant as to whether they are truly hudi project config or just onetable-hudi specific. So, currently creating interfaces for this configuration classes that are in the table specific packages in the core module. Also, ignoring a nagging question in the back of my mind regarding versioning of table formats. This may need to be added to the ServiceLoader mechanism as well. So instead of just name maybe we add a name+version with a default version being the latest OR we just assume if there are incompatible changes that a new TableFormatName will be used for the new version.

In terms of programming model, if the canonical pattern will be a single source to one or more targets that can be identified only by TableFormatNames then I can't imagine a reason that the caller should have to do any of the heavy lifting of creating and initializing the clients themselves - just let the factory do it internally.

If there are other usecase patterns that are less obvious but requires greater level of control then you could support both patterns at the same time.

Anyway, this is turning into a non-trivial change. My current effort here may be a first iteration or just a discovery phase to inform a future effort.

**Comment by lmccay** [comment]
@the-other-tim-brown - The various table Client classes have ctor's that seem to enable the level of control where an application can pass in an existing spark session or have a new one built if they don't pass one in. The factory however only supports the latter. Is there a document or tests cases representing actual enduser usecases that don't use the factory for the target client creations?

I have managed to add the ServiceLoader pattern for DeltaClient already and it works fine. Have to figure out how to refactor the ctor's and init() to work together and this detail is important for that refactoring.

**Comment by the-other-tim-brown** [comment]
@lmccay based on your PR, the factory approach should work just fine. I was just wondering if it would be easier to pass in the TargetClients to the sync method. Right now I don't know of anyone with a custom Target or Source but the idea was to leave the possibility open.

**Comment by lmccay** [comment]
@the-other-tim-brown - is this issue complete now that the factory is in place or are we waiting on the refactoring of the config file?

**Comment by the-other-tim-brown** [comment]
@ashvina I'll defer to you as the original author of the issue.

**Comment by ashvina** [comment]
Yes, the `ServiceLoader` integration addresses this issue. I am marking this issue as closed.
Thanks @lmccay
