### ISSUE TITLE
Create Slack Channel or group for OneTable 

### ISSUE THREAD

**Issue by soumilshah1995** [onetable-io/onetable#243]
hello I was thinking we should create slack channel or group for OneTable

**Comment by jcamachor** [comment]
Thanks for creating this issue, @soumilshah1995 . This is a great idea. In fact, we already have a Teams group that was not public since the project had not been open sourced yet. @ashvina , I believe you created the group. Do you think we could make it public now, maybe add the link to the OneTable website / GH repo?

**Comment by soumilshah1995** [comment]
Thanks Heads up

**Comment by kywe665** [comment]
I'd like to see more upvotes for a discussion app before we add one. I think it's healthy for the project in the early days to facilitate more of the discussion through GitHub? We have github discussions feature on which can be used for Q&A, sharing of ideas, and more. Does that work for now?

**Comment by soumilshah1995** [comment]
Sure
